type Calendar = GoogleAppsScript.Calendar.Calendar
type CalendarEvent = GoogleAppsScript.Calendar.CalendarEvent

function eventFilter(calendar: Calendar, startDate: Date, endDate: Date) {
    // get events then filter them to exclude "undefined" events (i don't know why they exist)
    const eventsArray: Array<CalendarEvent> = calendar.getEvents(startDate, endDate).filter(event => event !== undefined)
    
    // distinguishes between all-day events and events with specific time
    let eventsStringArray: Array<String> = eventsArray.map(event => {
        if (event.isAllDayEvent()) {
            return `<p><span style="font-weight: bold;">No spec. time</span>: ${event.getTitle()}</p>`
        } else {
            const startTime = new Date(event.getStartTime().getTime())
            const endTime = new Date(event.getEndTime().getTime())
            
            // email formatting
            const options = {hour: '2-digit', minute: '2-digit'} as const
            return `<p><span style="font-weight: bold;">${startTime.toLocaleTimeString("en-PH", options)} - ${endTime.toLocaleTimeString("en-PH", options)}</span>: ${event.getTitle()}</p>`
        }
    })

    return eventsStringArray.join('\n')
}

// split by newlines then remove first and last element (which are empty strings)
let cleanEmails = ((emailList: String) => {
    return emailList.split('\n').slice(1, -1).map((str) => str.trim()).join(',')
})

function calendarReminderSystem() {
    // get calendar
    let calendar: Calendar = CalendarApp.getOwnedCalendarById(CALENDAR_ID)
    console.log(`Calendar: ${calendar.getName()}`)

    // get date
    let now = new Date()
    let nowMidnight = new Date(now.getTime())
    nowMidnight.setHours(0, 0, 0, 0)
    let endMidnight = new Date(nowMidnight.getTime() + RANGE * DAY)
    endMidnight.setHours(23, 59, 59, 999)
    console.log(`now: ${now.getTime()}, ${RANGE} from now: ${endMidnight.getTime()}`)

    // email addresses
    const sharedUsers = cleanEmails(EMAIL_ADDRESSES)
    console.log(`Users: ${sharedUsers}`)

    let htmlBody = ""
    htmlBody += `
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto:ital@0;1&display=swap');
    </style>
    <div style="font-family: Roboto, Arial, sans-serif; font-size: 1.2em">
        <p>Good day! These are the following events for the next 7 days, from now until ${endMidnight.toLocaleDateString("en-PH")}.</p>
        <br/><br/>
    `

    let currentDate = now
    while (currentDate.getTime() < endMidnight.getTime()) {
        let midnight = new Date(currentDate.getTime())
        midnight.setHours(23, 59, 59, 999)

        let sortedEvents = eventFilter(calendar, currentDate, midnight)
        console.log(currentDate.toLocaleDateString("en-PH", { year:"numeric", month:"short", day:"numeric" }))
        console.log(sortedEvents)

        htmlBody += `
        <p style="font-weight: bold; font-size: 1.5em;">
            ${currentDate.toLocaleDateString("en-PH", { year:"numeric", month:"short", day:"numeric" })} - 
            ${currentDate.toLocaleDateString("en-PH", { weekday: 'long' })}
        </p>
        <span>${sortedEvents}</span>
        <br/>
        `

        currentDate.setHours(0, 0, 0, 0)
        currentDate = new Date(currentDate.getTime() + 1 * DAY)
    }

    htmlBody += `
        <br/><p style="font-style: italic;">
            This message was generated by the Calendar Reminder System (CRS) using Google Apps Script, 
            Google Cloud Console in TypeScript. If there are any problems or concerns, please contact 
            <a href="mailto:juanvillegas070825@gmail.com">juanvillegas070825@gmail.com</a> or 
            <a href="mailto:406946150626@ncr2.deped.gov.ph">406946150626@ncr2.deped.gov.ph</a>. GitHub
            repository at <a href="https://github.com/unovil/CRS">github.com/unovil/CRS</a>.
        </p>
    </div>`

    MailApp.sendEmail(sharedUsers, `${isTesting?"TESTING::":""}Events for ${nowMidnight.toLocaleDateString("en-PH", { weekday: 'long', year:"numeric", month:"short", day:"numeric"})}`, "", {
        htmlBody: htmlBody,
        name: TITLE,
        cc: CC_EMAIL_ADDRESSES
    })
}
