type Calendar = GoogleAppsScript.Calendar.Calendar
type CalendarEvent = GoogleAppsScript.Calendar.CalendarEvent

function eventFilter(calendar: Calendar, startDate: Date, endDate: Date) {
    const eventsArray: Array<CalendarEvent> = calendar.getEvents(startDate, endDate).filter(event => event !== undefined)
    
    let eventsStringArray: Array<String> = eventsArray.map(event => {
        if (event.isAllDayEvent()) {
            return `<p><span style="font-weight: bold;">No spec. time</span>: ${event.getTitle()}</p>`
        } else {
            const startTime = new Date(event.getStartTime().getTime())
            const endTime = new Date(event.getEndTime().getTime())

            const options = {hour: '2-digit', minute: '2-digit'} as const
            return `<p><span style="font-weight: bold;">${startTime.toLocaleTimeString("en-PH", options)} - ${endTime.toLocaleTimeString("en-PH", options)}</span>: ${event.getTitle()}</p>`
        }
    })

    return eventsStringArray.join('\n')
}

let cleanEmails = ((emailList: String) => {
    return emailList.split('\n').slice(1, -1).map((str) => str.trim()).join(',')
})

function calendarReminderSystem() {
    // get calendar
    let calendar: Calendar = CalendarApp.getOwnedCalendarById(CALENDAR_ID)
    console.log(`Calendar: ${calendar.getName()}`)

    // get date
    let now = new Date()
    now.setHours(0, 0, 0, 0)
    let end = new Date(now.getTime() + 7 * DAY)
    end.setHours(23, 59, 59, 999)
    console.log(`now: ${now.getTime()}, 7 from now: ${end.getTime()}`)

    // email addresses
    const sharedUsers = cleanEmails(EMAIL_ADDRESSES)
    console.log(`Users: ${sharedUsers}`)

    let htmlBody = ""
    htmlBody += `
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto:ital@0;1&display=swap');
    </style>
    <div style="font-family: Roboto, Arial, sans-serif; font-size: 1.2em">
        <p>Good day! These are the following events for the next 7 days, from now until ${end.toLocaleDateString("en-PH")}.</p>
        <br/><br/>
    `
    
    for (
        let i = now; // i = current date
        i.getTime() < end.getTime(); // time of i is less than time of end
        i = new Date(i.getTime() + 1 * DAY) // time of i is added 1 full day
    ) {
        let sortedEvents = eventFilter(calendar, i, new Date(i.getTime() + 1 * DAY))
        htmlBody += `
        <p style="font-weight: bold; font-size: 1.5em;">
            ${i.toLocaleDateString("en-PH", { year:"numeric", month:"short", day:"numeric" })} - 
            ${i.toLocaleDateString("en-PH", { weekday: 'long' })}
        </p>
        <span>${sortedEvents}</span>
        <br/>
        `
    }

    htmlBody += `
        <br/><p style="font-style: italic;">
            This message was generated by the Calendar Reminder System (CRS) using Google Apps Script, 
            Google Cloud Console in TypeScript. If there are any problems or concerns, please contact 
            <a href="mailto:juanvillegas070825@gmail.com">juanvillegas070825@gmail.com</a> or 
            <a href="mailto:406946150626@ncr2.deped.gov.ph">406946150626@ncr2.deped.gov.ph</a>. GitHub
            repository at <a href="https://github.com/unovil/CRS">github.com/unovil/CRS</a>.
        </p>
    </div>`

    MailApp.sendEmail(sharedUsers, `Events for ${now.toLocaleDateString("en-PH", { weekday: 'long', year:"numeric", month:"short", day:"numeric"})}`, "", {
        htmlBody: htmlBody,
        name: TITLE,
        cc: CC_EMAIL_ADDRESSES
    })
}
